In [19]:
import numpy as np
import pandas as pd

In [2]:
np.arange(1, 15, 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
n = np.ones((5, 3))
n[:, 2] = [2, 5, 9, 5, 4]
n

array([[1., 1., 2.],
       [1., 1., 5.],
       [1., 1., 9.],
       [1., 1., 5.],
       [1., 1., 4.]])

In [4]:
r = np.random.randint(low=10, high=100, size=(5,3))
r

array([[29, 25, 45],
       [33, 93, 14],
       [78, 65, 14],
       [27, 48, 96],
       [48, 49, 17]])

In [5]:
r.sum()

681

In [6]:
even_r = r[r%2==0]
even_r

array([14, 78, 14, 48, 96, 48])

In [7]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [8]:
p = np.random.randint(low=10, high=100, size=3)
pp = np.random.randint(low=10, high=100, size=3)

In [9]:
p.dot(pp) #same as vector_vector_multiplication()

3744

In [10]:
r.dot(pp) #matrix-vector multiplication

array([3143, 4491, 5822, 4917, 4036])

In [11]:
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
R = np.random.randint(low=10, high=100, size=(5,5))
R

array([[39, 77, 49, 17, 30],
       [38, 33, 46, 80, 88],
       [32, 16, 56, 81, 90],
       [95, 28, 47, 59, 28],
       [92, 76, 66, 21, 17]])

In [13]:
R_inv = np.linalg.inv(R)
R_inv

array([[-0.05819086,  0.04874313, -0.02994667, -0.02751584,  0.05423372],
       [ 0.03543397,  0.00391558, -0.01522658,  0.01489772, -0.02672554],
       [ 0.03408284, -0.07457683,  0.06067811,  0.01531717, -0.02056676],
       [ 0.09245401, -0.06004915,  0.02341753,  0.07526753, -0.10025668],
       [-0.090025  ,  0.0824206 , -0.03436529, -0.07013654,  0.08849622]])

In [14]:
R_inv.dot(R)

array([[ 1.00000000e+00, -6.10622664e-16, -2.49800181e-16,
         4.16333634e-17, -5.68989300e-16],
       [ 8.46545056e-16,  1.00000000e+00,  5.20417043e-16,
        -8.67361738e-17, -6.83481050e-16],
       [-5.13478149e-16, -3.46944695e-16,  1.00000000e+00,
         1.70002901e-16,  1.48839274e-15],
       [ 5.55111512e-17,  2.05391260e-15,  1.08246745e-15,
         1.00000000e+00,  3.19189120e-16],
       [-1.33226763e-15, -1.33226763e-15, -1.11022302e-15,
         1.11022302e-16,  1.00000000e+00]])

In [16]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [17]:
df = pd.DataFrame(data, columns=columns)

In [18]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [24]:
df.loc[2]

Make                       Lotus
Model                      Elise
Year                        2010
Engine HP                  218.0
Engine Cylinders               4
Transmission Type         MANUAL
Vehicle_Style        convertible
MSRP                       54990
Name: 2, dtype: object

In [27]:
df[(df['Year'] >= 2010) & (df['MSRP'] >= 32340)]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [28]:
>>> df['Vehicle_Style'] = df['Vehicle_Style'].str.replace(' ', '_').str.lower()

In [29]:
>>> df.groupby('Transmission Type').MSRP.max()

Transmission Type
AUTOMATIC    34450
MANUAL       54990
Name: MSRP, dtype: int64

In [30]:
>>> df.to_dict(orient='records')

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 27150},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr_suv',
  'MSRP': 34450},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'pickup',
  'MSRP': 32340}]

In [31]:
pd.__version__

'1.5.0'